"use client";
import { FormEvent, useEffect, useState } from "react";
import styles from "./Agenda.module.css";
interface Curso{_id:string;nombre:string;division?:string} interface Evento{_id:string;tipo:string;titulo:string;descripcion?:string;fecha:string;hora?:string;cursoId?:Curso} interface Tarea{_id:string;materia:string;titulo:string;descripcion?:string;fechaEntrega:string;cursoId?:Curso}
export default function AgendaManager(){
 const[cursos,setCursos]=useState<Curso[]>([]),[eventos,setEventos]=useState<Evento[]>([]),[tareas,setTareas]=useState<Tarea[]>([]); const[tab,setTab]=useState<"evento"|"tarea">("evento"); const[cursoId,setCursoId]=useState(""); const[titulo,setTitulo]=useState(""); const[descripcion,setDescripcion]=useState(""); const[fecha,setFecha]=useState(""); const[hora,setHora]=useState(""); const[tipo,setTipo]=useState("evaluacion"); const[materia,setMateria]=useState(""); const[mensaje,setMensaje]=useState(""); const[guardando,setGuardando]=useState(false);
 async function cargar(){const[c,a]=await Promise.all([fetch('/api/cursos',{cache:'no-store'}),fetch('/api/agenda',{cache:'no-store'})]);const[cd,ad]=await Promise.all([c.json(),a.json()]);if(c.ok){setCursos(cd.cursos||[]);if(!cursoId&&cd.cursos?.length)setCursoId(cd.cursos[0]._id)}if(a.ok){setEventos(ad.eventos||[]);setTareas(ad.tareas||[])}}
 useEffect(()=>{cargar()},[]);
 async function guardar(e:FormEvent){e.preventDefault();setMensaje("");setGuardando(true);const body=tab==='evento'?{registro:'evento',cursoId,titulo,descripcion,fecha,hora,tipo}:{registro:'tarea',cursoId,titulo,descripcion,fechaEntrega:fecha,materia};const r=await fetch('/api/agenda',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();setGuardando(false);if(!r.ok){setMensaje(d.message||'No se pudo guardar.');return}setMensaje(tab==='evento'?'Evento publicado y familias notificadas.':'Tarea publicada y familias notificadas.');setTitulo('');setDescripcion('');setFecha('');setHora('');setMateria('');await cargar()}
 return <div className={styles.wrapper}><div className={styles.tabs}><button className={tab==='evento'?styles.active:''} onClick={()=>setTab('evento')}>📅 Evento</button><button className={tab==='tarea'?styles.active:''} onClick={()=>setTab('tarea')}>📝 Tarea</button></div><div className={styles.panel}><form className={styles.form} onSubmit={guardar}><label>Curso<select value={cursoId} onChange={e=>setCursoId(e.target.value)} required><option value="">Elegir curso</option>{cursos.map(c=><option key={c._id} value={c._id}>{c.nombre} {c.division||''}</option>)}</select></label>{tab==='evento'?<label>Tipo<select value={tipo} onChange={e=>setTipo(e.target.value)}><option value="evaluacion">Evaluación</option><option value="reunion">Reunión</option><option value="acto">Acto</option><option value="feriado">Feriado</option><option value="otro">Otro</option></select></label>:<label>Materia<input value={materia} onChange={e=>setMateria(e.target.value)} required /></label>}<label className={styles.full}>Título<input value={titulo} onChange={e=>setTitulo(e.target.value)} required /></label><label>{tab==='evento'?'Fecha':'Fecha de entrega'}<input type="date" value={fecha} onChange={e=>setFecha(e.target.value)} required /></label>{tab==='evento'&&<label>Hora (opcional)<input type="time" value={hora} onChange={e=>setHora(e.target.value)} /></label>}<label className={styles.full}>Descripción<textarea value={descripcion} onChange={e=>setDescripcion(e.target.value)} /></label><button className={styles.save} disabled={guardando}>{guardando?'Publicando...':'Publicar y notificar'}</button></form></div>{mensaje&&<div className={styles.message}>{mensaje}</div>}<div className={styles.list}>{[...eventos.map(x=>({kind:'evento' as const,date:x.fecha,item:x})),...tareas.map(x=>({kind:'tarea' as const,date:x.fechaEntrega,item:x}))].sort((a,b)=>a.date.localeCompare(b.date)).map(x=><article key={`${x.kind}-${x.item._id}`} className={styles.item}><div className={styles.date}>{x.date.slice(8,10)}<small>{x.date.slice(5,7)}</small></div><div><strong>{x.kind==='evento'?'📅':'📝'} {x.item.titulo}</strong>{x.kind==='tarea'&&<span>{(x.item as Tarea).materia}</span>}<small>{x.item.cursoId?`${x.item.cursoId.nombre} ${x.item.cursoId.division||''}`:''}{x.kind==='evento'&&(x.item as Evento).hora?` · ${(x.item as Evento).hora}`:''}</small>{x.item.descripcion&&<p>{x.item.descripcion}</p>}</div></article>)}</div></div>
}
